### ISSUE TITLE
Where my pictures at, yo?

### ISSUE THREAD

**Issue by maclennann** [maclennann/isnormonvistabreak.io#1]

**Comment by potashj** [comment]
Wow. Actually just hooked up my phone to get this going today. Incoming!!

**Comment by potashj** [comment]
@cleung2010 You too!

**Comment by maclennann** [comment]
Phew. I'm on a train between Sacramento and Chicago right now for 48 hours with nothing to do but write of Portland. And God knows I didn't take any of my own pictures, so there's no documentation after y'all left.

**Comment by calvn** [comment]
Sure thing

**Comment by potashj** [comment]
Check it.

**Comment by maclennann** [comment]
RIP my data plan, if I can get signal long enough to download all this.

**Comment by maclennann** [comment]
LGTM. Published as http://isnormonvistabreak.io/yes/2015/10/06/Portland/
