### ISSUE TITLE
Needs more content

### ISSUE THREAD

**Issue by jdaviscooke** [maclennann/isnormonvistabreak.io#3]
Something like a live stream of consciousness would be nice. Recommend setting up a heka (https://github.com/mozilla-services/heka) stream directly into the medulla oblongata

**Comment by muteldar** [comment]
Yeah this site is nice and all.. But really we need more content.

**Comment by maclennann** [comment]
See I had one set up earlier in the week, but it crashed hard on Wednesday around 2300 and I haven't brought it back up.

Though on a more-serious note, I should have better cell reception on my next leg between Chicago and DC than on any of the other two.

There are also several unpublished pictures that can be found in other  if you need some bonus content.
